name: Publish Package

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: 代码检出
        uses: actions/checkout@v4

#      - name: Install pnpm
#        uses: pnpm/action-setup@v2
#        with:
#          version: 8
#
#      - name: Install deps
#        run: pnpm i --no-frozen-lockfile --shamefully-hoist
#
#      - name: Use Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: 18
#          registry-url: 'https://registry.npmjs.org/'
#          cache: 'pnpm'

#      - name: Build
#        run: pnpm build:npm

      - name: 获取版本号
        run: |
          echo "version=$(grep -o '"version": *"[^"]*"' package.json | awk -F'"' '{print $4}')" >> "$GITHUB_ENV"

      - name: 是否是预发布
        run: |
          echo "prerelease=$([[ ${{ env.version }} == *-* ]] && echo 'true' || echo 'false')" >> "$GITHUB_ENV"

      - name: 打印信息
        run: |
          echo "version: ${{ env.version }}"
          echo "prerelease: ${{ env.prerelease }}"

      - name: 发布
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ env.version }}"
          draft: false
          prerelease: ${{ env.prerelease }}
          allowUpdates: true
          generateReleaseNotes: true
          token: ${{ secrets.TOKEN }}